<?php

namespace Database\Seeders;

use App\Models\DocumentTemplate;
use Illuminate\Database\Seeder;

class DocumentTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // ==================== SKRK ====================
            [
                'kode' => 'skrk_1a_form_survey',
                'nama' => '1A. Formulir Pemeriksaan Lapangan SKRK',
                'modul' => 'skrk',
                'default_path' => 'skrk/1A_Form_Survey_template.docx',
                'description' => 'Formulir survei lapangan untuk petugas pengukuran dan survei SKRK.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Lokasi Tanah',
                    'kel_tanah' => 'Kelurahan Lokasi Tanah',
                    'kec_tanah' => 'Kecamatan Lokasi Tanah',
                    'luas_tanah' => 'Luas Tanah Pemohon (m2)',
                    'fungsi_bangunan' => 'Fungsi / Rencana Bangunan',
                    'batas_barat' => 'Batas Barat Tanah',
                    'batas_timur' => 'Batas Timur Tanah',
                    'batas_utara' => 'Batas Utara Tanah',
                    'batas_selatan' => 'Batas Selatan Tanah',
                    'hari_survey' => 'Hari Pelaksanaan Survei (cth: Senin)',
                    'tgl_survey' => 'Tanggal Survei (terbilang, cth: Satu)',
                    'bulan_survey' => 'Bulan Pelaksanaan Survei (cth: Januari)',
                    'tahun_survey' => 'Tahun Survei (terbilang, cth: Dua Ribu Dua Puluh Enam)',
                ],
            ],
            [
                'kode' => 'skrk_1b_ba_survey',
                'nama' => '1B. Berita Acara Pemeriksaan Lapangan SKRK',
                'modul' => 'skrk',
                'default_path' => 'skrk/1B_BA_SURVEY_SKRK.docx',
                'description' => 'Berita Acara resmi hasil survei fisik lapangan oleh surveyor SKRK.',
                'available_variables' => [
                    'nama_surveyor' => 'Nama Petugas Surveyor',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Lokasi Tanah',
                    'kel_tanah' => 'Kelurahan Lokasi Tanah',
                    'kec_tanah' => 'Kecamatan Lokasi Tanah',
                    'luas_tanah' => 'Luas Tanah Pemohon (m2)',
                    'ada_bangunan' => 'Kondisi Eksisting (Ada / Tidak Ada Bangunan)',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'hari_survey' => 'Hari Survei',
                    'tgl_survey' => 'Tanggal Survei (terbilang)',
                    'bulan_survey' => 'Bulan Survei',
                    'tahun_survey' => 'Tahun Survei (terbilang)',
                    'tahun_number_survey' => 'Tahun Survei (angka)',
                    'status_jalan' => 'Status Jalan di Depan Lokasi',
                    'fungsi_jalan' => 'Fungsi Jalan (cth: Arteri, Kolektor, Lokal)',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Ada/Tidak Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan (meter)',
                ],
            ],
            [
                'kode' => 'skrk_2a_ba_rapat_fpr',
                'nama' => '2A. Berita Acara Rapat FPR SKRK',
                'modul' => 'skrk',
                'default_path' => 'skrk/2A_BA_rapat_fpr.docx',
                'description' => 'Berita Acara Rapat Forum Penataan Ruang terkait permohonan SKRK.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan Tanah',
                    'kec_tanah' => 'Kecamatan Tanah',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                ],
            ],
            [
                'kode' => 'skrk_2b_notulensi_rapat_fpr',
                'nama' => '2B. Notulensi Rapat FPR SKRK',
                'modul' => 'skrk',
                'default_path' => 'skrk/2B_notulensi_rapat_fpr.docx',
                'description' => 'Catatan dan notulensi pembahasan permohonan SKRK di Forum Penataan Ruang.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan Tanah',
                    'kec_tanah' => 'Kecamatan Tanah',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                ],
            ],
            [
                'kode' => 'skrk_3_kajian',
                'nama' => '3. Kajian Teknis SKRK',
                'modul' => 'skrk',
                'default_path' => 'skrk/3_kajian_skrk.docx',
                'description' => 'Dokumen kajian teknis dan tata ruang oleh tim analis SKRK.',
                'available_variables' => [
                    'nama_analis' => 'Nama Petugas Analis',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor / Kode Registrasi',
                    'nik' => 'NIK Pemohon',
                    'no_hp' => 'No HP / WhatsApp',
                    'email' => 'Email Pemohon',
                    'alamat_tanah' => 'Alamat Lokasi Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'ada_bangunan' => 'Status Ada Bangunan',
                    'koordinat' => 'Titik Koordinat (Teks)',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'status_jalan' => 'Status Jalan',
                    'fungsi_jalan' => 'Fungsi Jalan',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan',
                    'penguasaan_tanah' => 'Status Penguasaan Tanah',
                    'jml_bangunan' => 'Jumlah Bangunan',
                    'jml_lantai' => 'Jumlah Lantai',
                    'luas_lantai' => 'Luas Lantai',
                    'kedalaman_min' => 'Kedalaman Minimal',
                    'kedalaman_max' => 'Kedalaman Maksimal',
                    'kdb' => 'Koefisien Dasar Bangunan (KDB)',
                    'klb' => 'Koefisien Lantai Bangunan (KLB)',
                    'kdh' => 'Koefisien Daerah Hijau (KDH)',
                    'gsb' => 'Garis Sempadan Bangunan (GSB)',
                    'jba' => 'Jarak Bebas Antar Bangunan (JBA)',
                    'jbb' => 'Jarak Bebas Belakang (JBB)',
                    'ktb' => 'Koefisien Tapak Basement (KTB)',
                ],
            ],
            [
                'kode' => 'skrk_4_dokumen_skrk',
                'nama' => '4. Dokumen Surat Keterangan Rencana Kota (SKRK)',
                'modul' => 'skrk',
                'default_path' => 'skrk/4_dokumen_skrk.docx',
                'description' => 'Dokumen final Surat Keterangan Rencana Kota (SKRK) lengkap dengan tabel koordinat.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK Pemohon',
                    'no_hp' => 'No HP Pemohon',
                    'email' => 'Email Pemohon',
                    'npwp' => 'NPWP Pemohon/Badan',
                    'status_modal' => 'Status Permodalan (PMA/PMDN)',
                    'kbli' => 'Kode KBLI',
                    'judul_kbli' => 'Judul KBLI',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis/Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'skala_usaha' => 'Skala Usaha',
                    'luas_disetujui' => 'Luas yang Disetujui',
                    'pemanfaatan_ruang' => 'Pemanfaatan Ruang Sesuai RTRW',
                    'peraturan_zonasi' => 'Peraturan Zonasi',
                    'kbli_diizinkan' => 'KBLI yang Diizinkan',
                    'kdb' => 'KDB (%)',
                    'klb' => 'KLB',
                    'gsb' => 'GSB (meter)',
                    'jba' => 'JBA (meter)',
                    'jbb' => 'JBB (meter)',
                    'kdh' => 'KDH (%)',
                    'ktb' => 'KTB (%)',
                    'luas_kavling' => 'Luas Kavling Minimal',
                    'jaringan_utilitas' => 'Jaringan Utilitas Kota',
                    'ketinggian_bangunan_max' => 'Ketinggian Bangunan Maksimal (m/lantai)',
                    'persyaratan_pelaksanaan' => 'Persyaratan Pelaksanaan Teknis',
                    'x' => 'Koordinat Bujur / X (Row Cloned)',
                    'y' => 'Koordinat Lintang / Y (Row Cloned)',
                ],
            ],
            [
                'kode' => 'skrk_penolakan',
                'nama' => 'Surat Penolakan SKRK (Bila Tidak Sesuai)',
                'modul' => 'skrk',
                'default_path' => 'skrk/SURAT PENOLAKAN SKRK (BILA TIDAK SESUAI).docx',
                'description' => 'Surat penolakan penerbitan SKRK bila lokasi tidak sesuai dengan RTRW / ketentuan.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'kode_regis' => 'Kode Registrasi',
                    'tanggal_regis' => 'Tanggal Registrasi',
                ],
            ],

            // ==================== ITR ====================
            [
                'kode' => 'itr_1a_form_survey',
                'nama' => '1A. Formulir Isian Survei Lapangan ITR',
                'modul' => 'itr',
                'default_path' => 'itr/1A_Form_Survey_template.docx',
                'description' => 'Formulir isian pemeriksaan lapangan untuk layanan ITR.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Lokasi Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'luas_tanah' => 'Luas Tanah (m2)',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'hari_survey' => 'Hari Survei',
                    'tgl_survey' => 'Tanggal Survei (terbilang)',
                    'bulan_survey' => 'Bulan Survei',
                    'tahun_survey' => 'Tahun Survei (terbilang)',
                ],
            ],
            [
                'kode' => 'itr_1b_ba_survey',
                'nama' => '1B. Berita Acara Survei Lapangan ITR',
                'modul' => 'itr',
                'default_path' => 'itr/1B_BA_survey_template.docx',
                'description' => 'Berita Acara hasil survei lapangan untuk permohonan ITR.',
                'available_variables' => [
                    'nama_surveyor' => 'Nama Surveyor',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'luas_tanah' => 'Luas Tanah',
                    'ada_bangunan' => 'Ada / Tidak Ada Bangunan',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'hari_survey' => 'Hari Survei',
                    'tgl_survey' => 'Tanggal Survei',
                    'bulan_survey' => 'Bulan Survei',
                    'tahun_survey' => 'Tahun Survei',
                    'tahun_number_survey' => 'Tahun Survei (angka)',
                    'status_jalan' => 'Status Jalan',
                    'fungsi_jalan' => 'Fungsi Jalan',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan',
                ],
            ],
            [
                'kode' => 'itr_3_dokumen_new',
                'nama' => '3. Dokumen Informasi Tata Ruang (ITR Reguler)',
                'modul' => 'itr',
                'default_path' => 'itr/3_template_itr_new.docx',
                'description' => 'Dokumen hasil akhir layanan Informasi Tata Ruang (ITR).',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK Pemohon',
                    'no_hp' => 'No HP',
                    'email' => 'Email',
                    'npwp' => 'NPWP',
                    'status_modal' => 'Status Modal',
                    'kbli' => 'Kode KBLI',
                    'judul_kbli' => 'Judul KBLI',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'koordinat' => 'Daftar Koordinat',
                    'penguasaan_tanah' => 'Penguasaan Tanah',
                    'skala_usaha' => 'Skala Usaha',
                    'luas_disetujui' => 'Luas Disetujui',
                    'pemanfaatan_ruang' => 'Pemanfaatan Ruang',
                    'peraturan_zonasi' => 'Peraturan Zonasi',
                    'kbli_diizinkan' => 'KBLI Diizinkan',
                    'kdb' => 'KDB',
                    'klb' => 'KLB',
                    'gsb' => 'GSB',
                    'jba' => 'JBA',
                    'jbb' => 'JBB',
                    'kdh' => 'KDH',
                    'ktb' => 'KTB',
                    'luas_kavling' => 'Luas Kavling',
                    'jaringan_utilitas' => 'Jaringan Utilitas',
                    'persyaratan_pelaksanaan' => 'Persyaratan Pelaksanaan',
                    'x' => 'Tabel Koordinat X (Row Cloned)',
                    'y' => 'Tabel Koordinat Y (Row Cloned)',
                ],
            ],
            [
                'kode' => 'itr_3_dokumen_kkkpr_new',
                'nama' => '3. Dokumen Informasi Tata Ruang (ITR - KKKPR)',
                'modul' => 'itr',
                'default_path' => 'itr/3_template_itr_kkkpr_new.docx',
                'description' => 'Dokumen hasil akhir layanan Informasi Tata Ruang untuk ITR-KKKPR.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK Pemohon',
                    'no_hp' => 'No HP',
                    'email' => 'Email',
                    'npwp' => 'NPWP',
                    'status_modal' => 'Status Modal',
                    'kbli' => 'Kode KBLI',
                    'judul_kbli' => 'Judul KBLI',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'koordinat' => 'Koordinat',
                    'penguasaan_tanah' => 'Penguasaan Tanah',
                    'skala_usaha' => 'Skala Usaha',
                    'luas_disetujui' => 'Luas Disetujui',
                    'pemanfaatan_ruang' => 'Pemanfaatan Ruang',
                    'peraturan_zonasi' => 'Peraturan Zonasi',
                    'kbli_diizinkan' => 'KBLI Diizinkan',
                    'kdb' => 'KDB',
                    'klb' => 'KLB',
                    'gsb' => 'GSB',
                    'jba' => 'JBA',
                    'jbb' => 'JBB',
                    'kdh' => 'KDH',
                    'ktb' => 'KTB',
                    'luas_kavling' => 'Luas Kavling',
                    'jaringan_utilitas' => 'Jaringan Utilitas',
                    'persyaratan_pelaksanaan' => 'Persyaratan Pelaksanaan',
                    'x' => 'Tabel Koordinat X (Row Cloned)',
                    'y' => 'Tabel Koordinat Y (Row Cloned)',
                ],
            ],

            // ==================== KKPRB ====================
            [
                'kode' => 'kkprb_1_ba_lapangan',
                'nama' => '1. Berita Acara Pemeriksaan Lapangan KKPRB',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/1_BA_PEMERIKSAAN_LAPANGAN.docx',
                'description' => 'Berita acara pemeriksaan fisik lapangan KKPR Berusaha.',
                'available_variables' => [
                    'nama_surveyor' => 'Nama Surveyor',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'luas_tanah' => 'Luas Tanah',
                    'ada_bangunan' => 'Status Bangunan',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'hari_survey' => 'Hari Survei',
                    'tgl_survey' => 'Tanggal Survei',
                    'bulan_survey' => 'Bulan Survei',
                    'tahun_survey' => 'Tahun Survei',
                    'tahun_number_survey' => 'Tahun (angka)',
                    'status_jalan' => 'Status Jalan',
                    'fungsi_jalan' => 'Fungsi Jalan',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan',
                ],
            ],
            [
                'kode' => 'kkprb_2a_ba_rapat_fpr',
                'nama' => '2A. Berita Acara Rapat FPR KKPRB',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/2A_BA_RAPAT_FPR.docx',
                'description' => 'Berita Acara Rapat Forum Penataan Ruang KKPR Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                ],
            ],
            [
                'kode' => 'kkprb_2b_notulensi_rapat_fpr',
                'nama' => '2B. Notulensi Rapat FPR KKPRB',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/2B_NOTULENSI_RAPAT_FPR.docx',
                'description' => 'Notulensi Rapat Forum Penataan Ruang KKPR Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                ],
            ],
            [
                'kode' => 'kkprb_3_kajian',
                'nama' => '3. Kajian Teknis KKPR Berusaha',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/3_KAJIAN_KKPRB.docx',
                'description' => 'Kajian teknis komprehensif KKPR Berusaha oleh tim analis.',
                'available_variables' => [
                    'nama_analis' => 'Nama Analis',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK Pemohon',
                    'no_hp' => 'No HP',
                    'email' => 'Email',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'ada_bangunan' => 'Ada Bangunan',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'status_jalan' => 'Status Jalan',
                    'fungsi_jalan' => 'Fungsi Jalan',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan',
                    'penguasaan_tanah' => 'Penguasaan Tanah',
                    'kdb' => 'KDB',
                    'klb' => 'KLB',
                    'kdh' => 'KDH',
                    'gsb' => 'GSB',
                    'jba' => 'JBA',
                    'jbb' => 'JBB',
                    'ktb' => 'KTB',
                    'x' => 'Koordinat X (Row Cloned)',
                    'y' => 'Koordinat Y (Row Cloned)',
                ],
            ],
            [
                'kode' => 'kkprb_4_nota_dinas',
                'nama' => '4. Nota Dinas Kajian KKPR Berusaha',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/4_NOTA_DINAS_KAJIAN_KKPRB.docx',
                'description' => 'Nota Dinas hasil kajian KKPR Berusaha kepada pimpinan.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                ],
            ],
            [
                'kode' => 'kkprb_5_rekomendasi',
                'nama' => '5. Rekomendasi KKPR Berusaha',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/5_REKOMENDASI_KKPRB.docx',
                'description' => 'Rekomendasi Forum Penataan Ruang untuk KKPR Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                ],
            ],
            [
                'kode' => 'kkprb_6_format_persetujuan',
                'nama' => '6. Format Persetujuan KKPR Berusaha',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/6_FORMAT_PERSETUJUAN_KKPRB.docx',
                'description' => 'Format persetujuan resmi KKPR Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK',
                    'no_hp' => 'No HP',
                    'email' => 'Email',
                    'npwp' => 'NPWP',
                    'status_modal' => 'Status Permodalan',
                    'kbli' => 'KBLI',
                    'judul_kbli' => 'Judul KBLI',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'skala_usaha' => 'Skala Usaha',
                    'luas_disetujui' => 'Luas Disetujui',
                    'pemanfaatan_ruang' => 'Pemanfaatan Ruang',
                    'peraturan_zonasi' => 'Peraturan Zonasi',
                    'kbli_diizinkan' => 'KBLI Diizinkan',
                    'kdb' => 'KDB',
                    'klb' => 'KLB',
                    'gsb' => 'GSB',
                    'jba' => 'JBA',
                    'jbb' => 'JBB',
                    'kdh' => 'KDH',
                    'ktb' => 'KTB',
                    'luas_kavling' => 'Luas Kavling',
                    'jaringan_utilitas' => 'Jaringan Utilitas',
                    'ketinggian_bangunan_max' => 'Ketinggian Bangunan Max',
                    'persyaratan_pelaksanaan' => 'Persyaratan Pelaksanaan',
                    'x' => 'Koordinat X (Row Cloned)',
                    'y' => 'Koordinat Y (Row Cloned)',
                ],
            ],
            [
                'kode' => 'kkprb_surat_pengantar_non_umk',
                'nama' => 'Surat Pengantar KKPR Berusaha Non UMK',
                'modul' => 'kkprb',
                'default_path' => 'kkprb/Surat_Pengantar_KKPR_Berusaha_Non_UMK.docx',
                'description' => 'Surat Pengantar KKPR Berusaha kategori Non-UMK.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'nomor_surat' => 'Nomor Surat',
                    'tgl_surat' => 'Tanggal Surat',
                ],
            ],

            // ==================== KKPRNB ====================
            [
                'kode' => 'kkprnb_1a_tanggapan',
                'nama' => '1A. Formulir Tanggapan 1A KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/1A_TANGGAPAN_1A.docx',
                'description' => 'Surat tanggapan kelengkapan berkas tahap 1A KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                ],
            ],
            [
                'kode' => 'kkprnb_1b_tanggapan',
                'nama' => '1B. Formulir Tanggapan 1B KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/1B_TANGGAPAN_1B.docx',
                'description' => 'Surat tanggapan kelengkapan berkas tahap 1B KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                ],
            ],
            [
                'kode' => 'kkprnb_2_tanggapan',
                'nama' => '2. Formulir Tanggapan 2 KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/2_TANGGAPAN_2.docx',
                'description' => 'Surat tanggapan lanjutan tahap 2 KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                ],
            ],
            [
                'kode' => 'kkprnb_3a_ba_lapangan',
                'nama' => '3A. Berita Acara Pemeriksaan Lapangan KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/3A_BA_PEMERIKSAAN_LAPANGAN_NON_BERUSAHA.docx',
                'description' => 'Berita Acara pemeriksaan survei lapangan KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_surveyor' => 'Nama Surveyor',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'luas_tanah' => 'Luas Tanah',
                    'ada_bangunan' => 'Ada Bangunan',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'hari_survey' => 'Hari Survei',
                    'tgl_survey' => 'Tanggal Survei',
                    'bulan_survey' => 'Bulan Survei',
                    'tahun_survey' => 'Tahun Survei',
                    'tahun_number_survey' => 'Tahun (angka)',
                    'status_jalan' => 'Status Jalan',
                    'fungsi_jalan' => 'Fungsi Jalan',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan',
                ],
            ],
            [
                'kode' => 'kkprnb_3b_ba_rapat_fpr',
                'nama' => '3B. Berita Acara Rapat FPR KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/3B_BA_RAPAT_FPR_NON_BERUSAHA.docx',
                'description' => 'Berita Acara pembahasan di Forum Penataan Ruang KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                ],
            ],
            [
                'kode' => 'kkprnb_3c_notulensi_rapat_fpr',
                'nama' => '3C. Notulensi Rapat FPR KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/3C_NOTULENSI_RAPAT_FPR_NON_BERUSAHA.docx',
                'description' => 'Notulensi Rapat Forum Penataan Ruang KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                ],
            ],
            [
                'kode' => 'kkprnb_3d_kajian',
                'nama' => '3D. Kajian Teknis KKPR Non Berusaha',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/3D_KAJIAN_KKPR_NONBERUSAHA.docx',
                'description' => 'Kajian teknis komprehensif oleh tim analis KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_analis' => 'Nama Analis',
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK',
                    'no_hp' => 'No HP',
                    'email' => 'Email',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'ada_bangunan' => 'Ada Bangunan',
                    'batas_barat' => 'Batas Barat',
                    'batas_timur' => 'Batas Timur',
                    'batas_utara' => 'Batas Utara',
                    'batas_selatan' => 'Batas Selatan',
                    'status_jalan' => 'Status Jalan',
                    'fungsi_jalan' => 'Fungsi Jalan',
                    'tipe_jalan' => 'Tipe Jalan',
                    'median_jalan' => 'Median Jalan',
                    'lebar_jalan' => 'Lebar Jalan',
                    'penguasaan_tanah' => 'Penguasaan Tanah',
                    'kdb' => 'KDB',
                    'klb' => 'KLB',
                    'kdh' => 'KDH',
                    'gsb' => 'GSB',
                    'jba' => 'JBA',
                    'jbb' => 'JBB',
                    'ktb' => 'KTB',
                    'x' => 'Koordinat X (Row Cloned)',
                    'y' => 'Koordinat Y (Row Cloned)',
                ],
            ],
            [
                'kode' => 'kkprnb_4_nota_dinas',
                'nama' => '4. Nota Dinas Kajian KKPR Non Berusaha',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/4_NOTA_DINAS_KKPR_NON_BERUSAHA.docx',
                'description' => 'Nota Dinas telaah hasil kajian KKPR Non-Berusaha kepada pimpinan.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                ],
            ],
            [
                'kode' => 'kkprnb_5_rekomendasi',
                'nama' => '5. Rekomendasi KKPR Non Berusaha',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/5_REKOMENDASI_KKPR_NON_BERUSAHA.docx',
                'description' => 'Rekomendasi Forum Penataan Ruang untuk KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                ],
            ],
            [
                'kode' => 'kkprnb_6_format_persetujuan',
                'nama' => '6. Format Persetujuan KKPR Non Berusaha',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/6_FORMAT_PERSETUJUAN_KKPR_NONBERUSAHA.docx',
                'description' => 'Format persetujuan resmi KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'tanggal_regis' => 'Tanggal Registrasi',
                    'kode_regis' => 'Nomor Registrasi',
                    'nik' => 'NIK',
                    'no_hp' => 'No HP',
                    'email' => 'Email',
                    'alamat_tanah' => 'Alamat Tanah',
                    'kel_tanah' => 'Kelurahan',
                    'kec_tanah' => 'Kecamatan',
                    'jenis_bangunan' => 'Jenis Bangunan',
                    'luas_tanah' => 'Luas Tanah',
                    'skala_usaha' => 'Skala Usaha',
                    'luas_disetujui' => 'Luas Disetujui',
                    'pemanfaatan_ruang' => 'Pemanfaatan Ruang',
                    'peraturan_zonasi' => 'Peraturan Zonasi',
                    'kdb' => 'KDB',
                    'klb' => 'KLB',
                    'gsb' => 'GSB',
                    'jba' => 'JBA',
                    'jbb' => 'JBB',
                    'kdh' => 'KDH',
                    'ktb' => 'KTB',
                    'luas_kavling' => 'Luas Kavling',
                    'jaringan_utilitas' => 'Jaringan Utilitas',
                    'ketinggian_bangunan_max' => 'Ketinggian Bangunan Max',
                    'persyaratan_pelaksanaan' => 'Persyaratan Pelaksanaan',
                    'x' => 'Koordinat X (Row Cloned)',
                    'y' => 'Koordinat Y (Row Cloned)',
                ],
            ],
            [
                'kode' => 'kkprnb_ceklist',
                'nama' => 'Ceklist Kelengkapan Dokumen KKPRNB',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/Ceklist.docx',
                'description' => 'Lembar ceklist verifikasi berkas permohonan KKPR Non-Berusaha.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'kode_regis' => 'Kode Registrasi',
                    'tanggal_regis' => 'Tanggal Registrasi',
                ],
            ],
            [
                'kode' => 'kkprnb_pengantar_persetujuan_pertek',
                'nama' => 'Surat Pengantar Persetujuan KKPR NB (Dengan Pertek)',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/SURAT_PENGANTAR_PERSETUJUAN_KKPR_NB_DENGAN_PERTEK.docx',
                'description' => 'Surat pengantar persetujuan KKPR NB yang melampirkan Pertimbangan Teknis (Pertek).',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'nomor_surat' => 'Nomor Surat',
                    'tgl_surat' => 'Tanggal Surat',
                ],
            ],
            [
                'kode' => 'kkprnb_pengantar_persetujuan_non_pertek',
                'nama' => 'Surat Pengantar Persetujuan KKPR NB (Non Pertek)',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/SURAT_PENGANTAR_PERSETUJUAN_KKPR_NB_NON_PERTEK.docx',
                'description' => 'Surat pengantar persetujuan KKPR NB tanpa pertimbangan teknis pertanahan.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'nomor_surat' => 'Nomor Surat',
                    'tgl_surat' => 'Tanggal Surat',
                ],
            ],
            [
                'kode' => 'kkprnb_pengantar_kelengkapan_pertek',
                'nama' => 'Surat Pengantar Tanggapan Berkas (Dengan Pertek)',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/SURAT_PENGANTAR_TANGGAPAN_KELENGKAPAN_BERKAS_DENGAN_PERTEK.docx',
                'description' => 'Surat pengantar tanggapan kelengkapan berkas untuk proses dengan Pertek.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'nomor_surat' => 'Nomor Surat',
                    'tgl_surat' => 'Tanggal Surat',
                ],
            ],
            [
                'kode' => 'kkprnb_pengantar_kelengkapan_non_pertek',
                'nama' => 'Surat Pengantar Tanggapan Berkas (Non Pertek)',
                'modul' => 'kkprnb',
                'default_path' => 'kkprnb/SURAT_PENGANTAR_TANGGAPAN_KELENGKAPAN_BERKAS_NON_PERTEK.docx',
                'description' => 'Surat pengantar tanggapan kelengkapan berkas untuk proses tanpa Pertek.',
                'available_variables' => [
                    'nama_pemohon' => 'Nama Pemohon',
                    'alamat_pemohon' => 'Alamat Pemohon',
                    'nomor_surat' => 'Nomor Surat',
                    'tgl_surat' => 'Tanggal Surat',
                ],
            ],

            // ==================== PELANGGARAN ====================
            [
                'kode' => 'pelanggaran_ba_pengambilan_dokumen_1',
                'nama' => '1. BA Pengambilan Dokumen Pelanggaran',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/1_BA_PENGAMBILAN_DOKUMEN.docx',
                'description' => 'Berita Acara pengambilan dokumen kasus dugaan pelanggaran pemanfaatan ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                ],
            ],
            [
                'kode' => 'pelanggaran_ba_penolakan_2',
                'nama' => '2. BA Penolakan Pelanggaran',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/2_BA_PENOLAKAN.docx',
                'description' => 'Berita Acara penolakan pemeriksaan oleh pihak yang terindikasi melanggar.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                ],
            ],
            [
                'kode' => 'pelanggaran_ba_survei_lapangan_3a',
                'nama' => '3A. BA Survei Lapangan Pelanggaran',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/3A_BA_SURVEI_LAPANGAN.docx',
                'description' => 'Berita Acara survei lapangan investigasi pelanggaran pemanfaatan ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan / Pelanggar',
                    'latitude' => 'Koordinat Latitude',
                    'longitude' => 'Koordinat Longitude',
                    'gmaps' => 'Link Google Maps',
                    'alamat_pelanggar' => 'Alamat Domisili Pelanggar',
                    'kel_pelanggar' => 'Kelurahan Pelanggar',
                    'kec_pelanggar' => 'Kecamatan Pelanggar',
                    'kota_pelanggar' => 'Kota Pelanggar',
                    'prov_pelanggar' => 'Provinsi Pelanggar',
                ],
            ],
            [
                'kode' => 'pelanggaran_ba_survei_surveyor_3b',
                'nama' => '3B. BA Survei Lapangan Surveyor',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/3B_BA_SURVEI_LAPANGAN_SURVEYOR.docx',
                'description' => 'Berita Acara hasil survei lapangan dari tim surveyor teknis.',
                'available_variables' => [
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                ],
            ],
            [
                'kode' => 'pelanggaran_ba_wawancara_4a',
                'nama' => '4A. BA Wawancara / Klarifikasi',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/4A_BA_WAWANCARA.docx',
                'description' => 'Berita Acara wawancara dan klarifikasi dengan pihak pelanggar / saksi.',
                'available_variables' => [
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                ],
            ],
            [
                'kode' => 'pelanggaran_ba_penerapan_sanksi_5',
                'nama' => '5. BA Penerapan Sanksi Administratif',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/5_BA_PENERAPAN_SANKSI.docx',
                'description' => 'Berita Acara penerapan sanksi administratif tata ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'alamat_pelanggaran' => 'Alamat Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan Pelanggaran',
                    'kec_pelanggaran' => 'Kecamatan Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                    'alamat_pelanggar' => 'Alamat Domisili Pelanggar',
                    'kel_pelanggar' => 'Kelurahan Domisili',
                    'kec_pelanggar' => 'Kecamatan Domisili',
                    'kota_pelanggar' => 'Kota Domisili',
                    'prov_pelanggar' => 'Provinsi Domisili',
                ],
            ],
            [
                'kode' => 'pelanggaran_ba_sosialisasi_6',
                'nama' => '6. BA Sosialisasi Pelanggaran',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/6_BA_SOSIALISASI.docx',
                'description' => 'Berita Acara sosialisasi aturan penataan ruang kepada pelanggar.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'alamat_pelanggaran' => 'Alamat Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan Pelanggaran',
                    'kec_pelanggaran' => 'Kecamatan Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                ],
            ],
            [
                'kode' => 'pelanggaran_sk_sanksi_pemberhentian_10',
                'nama' => '10. SK Sanksi Pemberhentian Kegiatan',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/10_SK_SANKSI_PEMBERHENTIAN.docx',
                'description' => 'Surat Keputusan sanksi administratif penghentian sementara kegiatan/bangunan.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan Pelanggaran',
                    'kec_pelanggaran' => 'Kecamatan Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                ],
            ],
            [
                'kode' => 'pelanggaran_sp1',
                'nama' => 'Surat Peringatan 1 (SP 1)',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/SURAT_PERINGATAN_1.docx',
                'description' => 'Surat Peringatan Pertama atas dugaan pelanggaran tata ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pelanggar / Pemilik Bangunan',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'jenis_pemanfaatan_ruang' => 'Jenis Pemanfaatan Ruang',
                ],
            ],
            [
                'kode' => 'pelanggaran_sp2',
                'nama' => 'Surat Peringatan 2 (SP 2)',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/SURAT_PERINGATAN_2.docx',
                'description' => 'Surat Peringatan Kedua tindak lanjut pelanggaran tata ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pelanggar / Pemilik Bangunan',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'jenis_pemanfaatan_ruang' => 'Jenis Pemanfaatan Ruang',
                ],
            ],
            [
                'kode' => 'pelanggaran_sp3',
                'nama' => 'Surat Peringatan 3 (SP 3)',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/SURAT_PERINGATAN_3.docx',
                'description' => 'Surat Peringatan Ketiga (Terakhir) sebelum pelimpahan berkas sanksi.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pelanggar / Pemilik Bangunan',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'jenis_pemanfaatan_ruang' => 'Jenis Pemanfaatan Ruang',
                ],
            ],
            [
                'kode' => 'pelanggaran_pelimpahan_polpp',
                'nama' => 'Surat Pelimpahan Berkas ke SATPOL PP',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/SURAT_PELIMPAHAN_BERKAS_POLPP.docx',
                'description' => 'Surat pelimpahan penegakan hukum dan eksekusi sanksi ke Satpol PP.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pelanggar',
                    'alamat_pelanggaran' => 'Alamat Lokasi Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'jenis_pemanfaatan_ruang' => 'Jenis Pemanfaatan Ruang',
                ],
            ],
            [
                'kode' => 'pelanggaran_pernyataan',
                'nama' => 'Surat Pernyataan Pelanggaran Pemanfaatan Ruang',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/SURAT_PERNYATAAN_PELANGGARAN_PEMANFAATAN_RUANG.docx',
                'description' => 'Surat pernyataan kesanggupan/pengakuan dari pihak pelanggar tata ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                    'alamat_pelanggaran' => 'Alamat Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'jenis_pemanfaatan_ruang' => 'Jenis Pemanfaatan Ruang',
                ],
            ],
            [
                'kode' => 'pelanggaran_sosialisasi',
                'nama' => 'Surat Sosialisasi Pelanggaran Pemanfaatan Ruang',
                'modul' => 'pelanggaran',
                'default_path' => 'pelanggaran/SURAT_SOSIALISASI_PELANGGARAN.docx',
                'description' => 'Surat resmi sosialisasi dan edukasi ketentuan tata ruang.',
                'available_variables' => [
                    'jenis_indikasi_pelanggaran' => 'Jenis Indikasi Pelanggaran',
                    'nama_pemilik_bangunan' => 'Nama Pemilik Bangunan',
                    'alamat_pelanggaran' => 'Alamat Pelanggaran',
                    'kel_pelanggaran' => 'Kelurahan',
                    'kec_pelanggaran' => 'Kecamatan',
                    'jenis_pemanfaatan_ruang' => 'Jenis Pemanfaatan Ruang',
                ],
            ],

            // ==================== REGISTRASI ====================
            [
                'kode' => 'registrasi_tanda_terima',
                'nama' => 'Tanda Terima Registrasi Permohonan',
                'modul' => 'registrasi',
                'default_path' => 'skrk/Tanda_terima_registrasi.docx',
                'description' => 'Bukti tanda terima registrasi berkas permohonan yang diberikan kepada pemohon.',
                'available_variables' => [
                    'kode' => 'Kode Registrasi Permohonan',
                    'nama_pemohon' => 'Nama Pemohon',
                    'nik' => 'NIK Pemohon',
                    'no_hp' => 'Nomor HP Pemohon',
                    'email' => 'Email Pemohon',
                    'alamat_pemohon' => 'Alamat Domisili Pemohon',
                    'alamat_tanah' => 'Alamat Lengkap Lokasi Tanah',
                    'fungsi_bangunan' => 'Fungsi Bangunan',
                    'tgl_permohonan' => 'Tanggal Permohonan (dd-mm-yyyy)',
                    'jenis_layanan' => 'Nama Jenis Layanan (SKRK / ITR / KKPR)',
                    'penerima' => 'Nama Petugas CS / Penerima Berkas',
                ],
            ],
        ];

        foreach ($templates as $data) {
            DocumentTemplate::updateOrCreate(
                ['kode' => $data['kode']],
                $data
            );
        }
    }
}
